name: Test E2E

on:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test-e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test E2E
        uses: cypress-io/github-action@v5
        with:
          build: npm run build
          start: npx http-server --port 80 ./dist
          wait-on: http://localhost
 